# Linear Regression

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [4]:
df = pd.read_csv("homeprices-multiple.csv")
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4  4000         5    8  760000
5  4100         6    8  810000

In [7]:
X = df.drop('price',axis='columns')
X.values

array([[2600,    3,   20],
       [3000,    4,   15],
       [3200,    3,   18],
       [3600,    3,   30],
       [4000,    5,    8],
       [4100,    6,    8]])

In [8]:
y = df.price
y.values

array([550000, 565000, 610000, 595000, 760000, 810000])

In [9]:
linear_model = linear_model.LinearRegression()
linear_model.fit(X, y)
linear_model.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [10]:
linear_model.intercept_

np.float64(256461.14864864905)

In [13]:
linear_model.predict([[3000, 3,1],[4000, 4,2], [5000, 5,3]])

e:\GenAI_Learning\Apr2025\AgenticWS\april2025venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([650582.77027027, 779151.78571429, 907720.8011583 ])